workspace:
  base: /srv/app
  path: src/github.com/go-gitea/lgtm

pipeline:
  test:
    image: webhippie/golang:edge
    pull: true
    group: testing
    environment:
      GOPATH: /srv/app
      CGO_ENABLED: "1"
    commands:
      - make clean
      - make vet
      - make lint
      - make test
      - make build
    when:
      event: [ push, tag, pull_request ]

  test-mysql:
    image: webhippie/golang:edge
    pull: true
    group: testing
    commands:
      - make test-mysql
    when:
      event: [ push ]

  test-pgsql:
    image: webhippie/golang:edge
    pull: true
    group: testing
    commands:
      - make test-pgsql
    when:
      event: [ push ]

  coverage:
    image: plugins/codecov
    name: ${DRONE_REPO}
    secrets: [ codecov_token ]
    when:
      event: [ push, pull_request ]

  updater:
    image: appleboy/golang-testing:1.9.2
    pull: true
    commands:
      - make release
    when:
      event: [ tag ]

  updater:
    image: appleboy/golang-testing:1.9.2
    pull: true
    commands:
      - make release
    when:
      event: [ push ]
      branch: [ master ]

  docker:
    image: plugins/docker:17.05
    pull: true
    secrets: [ docker_username, docker_password ]
    group: release
    repo: gitea/lgtm
    auto_tag: true
    dockerfile: Dockerfile
    when:
      event: [ push, tag ]

  release:
    image: plugins/s3:1
    pull: true
    secrets: [ aws_access_key_id, aws_secret_access_key ]
    bucket: releases
    endpoint: https://storage.gitea.io
    path_style: true
    strip_prefix: dist/release/
    source: dist/release/*
    target: /lgtm/master
    when:
      event: [ push ]
      branch: [ master ]

  release:
    image: plugins/s3:1
    pull: true
    secrets: [ aws_access_key_id, aws_secret_access_key ]
    bucket: releases
    endpoint: https://storage.gitea.io
    path_style: true
    strip_prefix: dist/release/
    source: dist/release/*
    target: /lgtm/${DRONE_TAG##v}
    when:
      event: [ tag ]

  github:
    image: plugins/github-release:1
    pull: true
    secrets: [ github_token ]
    files:
      - dist/release/*
    when:
      event: [ tag ]

  discord:
    image: appleboy/drone-discord
    secrets: [ discord_webhook_id, discord_webhook_token ]
    when:
      event: [ push, tag, pull_request ]
      status: [ changed, failure ]

services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    when:
      event: [ push ]

  pgsql:
    image: postgres:9.5
    environment:
      - POSTGRES_DB=test
    when:
      event: [ push ]
